services:
    nginx:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker-configs/nginx/app.conf:/etc/nginx/conf.d/default.conf

    db:
        image: mysql:8.0-debian
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
    redis:
        image: redis:alpine

    app:
        build:
            context: .
            dockerfile: Dockerfile
        command: "php-fpm"
        env_file:
            - .env
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - db
            - nginx
            - redis

volumes:
    mysql_data:
        driver: local
